# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Zoluxiones' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Zoluxiones

pod 'Alamofire', '~> 5.4'
pod 'SwiftyJSON' 
pod 'NVActivityIndicatorView', '~> 4.8.0'

end
